name: Test_project

on:
    pull_request:
        branches:
            -main
jobs:
    test:
        runs-on: ubuntu-latest
        container: 
            image: node:18
        steps:
            - uses: actions/checkout@v3
              with:
                node-version: 18
            - run: npm ci
            - run: npm test
            - run: npm run build


   